#!/bin/sh

needMount="false"
if [ -z $(awk '{ if ($2 == "/boot") print $2 }' /proc/mounts) ]; then
	needMount="true"
	echo "Mounting /boot"
	mount /boot
fi

iucode_tool -S --write-earlyfw=/boot/microcode.cpio /lib/firmware/intel-ucode/*

if [ "$needMount" = "true" ]; then
	echo "Unmounting /boot"
	umount /boot
fi

